[project]
name = "middle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "filelock>=3.20.0",
    "markupsafe>=3.0.3",
    "numpy>=2.3.4",
    "torch>=2.8.0",
    "transformers>=4.57.1",
]
